All:
	cd src/Game ; javac main.java
	mv ./src/Game*.class ./bin
	mv ./src/Grapichs*.class ./bin
	mv ./src/Items/*.class ./bin/Items
	mv ./src/Characters/*.class ./bin/Characters
	mv ./src/Time/*.class ./bin/Time
	cd ..
	
run:
	cd bin ; java main
	cd ..

